### ISSUE TITLE
能否加上随机文章功能

### ISSUE THREAD

**Issue by anselmwang** [idealclover/Caritas-APP#3]
非常感谢您开发这个app，我现在每天使用。

我觉得jh文章可以随意的读，慢慢的就进了心里。

请问您能否开发一个随机文章按钮，可以预先配置某些类别，然后每次点击按钮都在这些类别中随机选择一篇文章？

很抱歉我不会移动app开发，没法直接贡献。

**Comment by idealclover** [comment]
2.1.0版本即将支持增加该功能

**Comment by idealclover** [comment]
https://zhuanlan.zhihu.com/p/563633615 done

**Comment by anselmwang** [comment]
非常感谢，我已经用上新版啦！
